### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by ppxb** [WhiteMinds/trial-tower#1]
以下是个人的一点疑问：
1. 游戏的状态机是否应该直接由引擎接管？
2. 事件的分发可否采用GameManager的形式调度？
3. 所有Model依靠模板的方式生成是否局限性太大？考虑JSON或EXCEL可能会比较灵活。
4. combatLog可以encode减少体积。
5. 最大的困惑是引擎类的实例为什么一定要传Character进去？
谢谢。

**Comment by WhiteMinds** [comment]
> 以下是个人的一点疑问：
> 
> 1. 游戏的状态机是否应该直接由引擎接管？
> 2. 事件的分发可否采用GameManager的形式调度？
> 3. 所有Model依靠模板的方式生成是否局限性太大？考虑JSON或EXCEL可能会比较灵活。
> 4. combatLog可以encode减少体积。
> 5. 最大的困惑是引擎类的实例为什么一定要传Character进去？
>    谢谢。

1. 我不确定我是否理解了你的问题，你的意思可能是指 randomCombat 的调用是否应该由引擎内部自发的周期性调用？等我们明确了问题的边界后再讨论它。

2. 我不知道我们理解的 GameManager 是不是一个东西，因为我其实没什么引擎的设计经验，我暂且认为你指的是一个 engine.eventBus 之类的事件总线模式。
我个人不太偏向事件总线的模式，就我的开发经验来看，简单来说，这种模式的可维护性、代码可读性是比直接的做出生命周期函数调用要差的。好处就是它在写的时候很方便。
可能还有一些其他方面的考虑，但我一时没记起来，比如事件模式在类型系统上做起来会更复杂一点，调用的顺序更加隐蔽之类的。
所以我会尽量少的去使用事件总线这种设计，除非它的产出比在某个场景下非常大，我才会去使用它实现一部分。

3. 你说的 Model 是指最原始的几个 Item、Entity 的模型，还是指他们衍生出来的模板（template）？
我感觉你说的可能是模板，那一块确实在新增时会麻烦一点，不过我还没有完全总结出每个模板的共同点。
所以需要等后面真的开始做内容的时候，大量写模板时我感受到它们的缺点，我再去改进。

4. 消息体的传输体积确实是个问题，不过准备先把核心的理念实现好，优化可以放到中后期再考虑。
这个的优化其实是想过一些方案的，比如为 Logs 准备一个 Outgoing 的结构，然后调用 Logs.toOutgoing(logs) 转换成一个特殊的结构体（itemMap + logs 之类的），在准备读取内容时再转换成方便操作的格式。

5. 因为我一开始考虑的是一个引擎对应一个角色实例，服务端持有多个引擎实例，角色退出之后直接销毁对应引擎实例会比较方便。
后来考虑了一些情况之后，又决定还是一个引擎对应多个实例了，有一部分简略的思考过程写在了 RoadMap 中。
最新的代码已经是单引擎多实例了，你可以看看。

**Comment by ppxb** [comment]
您好，没想到这么快就收到了您的回复。
1. 我的意思可能表达的不太明确。就我浅薄的知识来讲，游戏引擎可能需要一套自有逻辑对内部实例进行初始化以及事件的调度和分发，可能和eventbus还不太一样。但这不等于一定要如此做，我只是在阅读您的代码时产生了一些疑问。任何的项目仅依赖个人的编码风格，这是无可厚非的。
2. 我指的是您的代码中的衍生template。可能现在处于项目初期，这种做法对测试或逻辑的演练会有一定帮助。当然我仅仅提出一些不成熟的建议，如果能够进行模板化的解析可能会是更好的方案。
3. 此前我在做类似项目的时候，因为要涉及load、save等常用的持久化功能，但json实在太过冗余，我选择了lzstring来进行encode以减少字符串体积。
4. 您提到的多实例我还没看到，我是从您的commit从头开始阅读的，可能产生了误解，对此感到抱歉。

我是一个偏爱idle game的普通玩家，且对diablo like的游戏有很强的亲切感。在github上看到您的项目便产生了浓厚的兴趣，如果我的留言对您有冒犯之处，敬请谅解。

**Comment by WhiteMinds** [comment]
> 您好，没想到这么快就收到了您的回复。
> 
> 1. 我的意思可能表达的不太明确。就我浅薄的知识来讲，游戏引擎可能需要一套自有逻辑对内部实例进行初始化以及事件的调度和分发，可能和eventbus还不太一样。但这不等于一定要如此做，我只是在阅读您的代码时产生了一些疑问。任何的项目仅依赖个人的编码风格，这是无可厚非的。
> 2. 我指的是您的代码中的衍生tamplate。可能现在处于项目初期，这种做法对测试或逻辑的演练会有一定帮助。当然我仅仅提出一些不成熟的建议，如果能够进行模板化的解析可能会是更好的方案。
> 3. 此前我在做类似项目的时候，因为要涉及load、save等常用的持久化功能，但json实在太过冗余，我选择了lzstring来进行encode以减少字符串体积。
> 4. 您提到的多实例我还没看到，我是从您的commit从头开始阅读的，可能产生了误解，对此感到抱歉。
> 
> 我是一个偏爱idle game的普通玩家，且对diablo like的游戏有很强的亲切感。在github上看到您的项目便产生了浓厚的兴趣，如果我的留言对您有冒犯之处，敬请谅解。

首先，可以不用 `您`，感觉有点抬举我了 🤪
这么快回复是因为我很开心有人关注这个项目。

1. 我对于游戏开发没什么经验，这是我第一次尝试，应该会有很多不足之处，你愿意提出建议我很开心，因为这可能会让我更多的去思考一些遗漏的点。
2. 这个以后再想想，现在我卡在了引擎比较核心的部分（数据存储时的完整性）。
3. 看了下 lzstring，是和结构无关的字符串压缩库，我感觉你可能是想用在 ServerStore 那个部分？
其实后面是准备改成完全的结构化存储到数据库的，不是直接的 json 字符串，能用到的地方大概就是 engine 内部的传输了以及和浏览器客户端的传输了，内部传输多了一层 encode 的话感觉性价比不高，到客户端传输的话可以直接通过 gzip 替代。
4. 啊这，因为目前还是比较原始的架构设计阶段，所以很多 commit 我可能是修修改改，前面加后面删，阅读体验应该不太好 🌚

我也是 idle game + diablo like 😆，几次想动手开始写不过都因为闲暇时间不多而打断了，这次准备坚持久一点，至少搞个勉强可玩的版本。
没有什么冒犯的，我感觉用词都比较中性，只是上下文不够多导致我有些地方不能理解意思。

**Comment by ppxb** [comment]
我也曾多次萌发想要开发一款类似的text-based-idle-game,但是因为繁杂的事务让我无暇分心。
在称呼上，关于`您`大可不必在意，这是基本的尊重。
1. lzstring可以对JSON.stringfy后的结构化数据编码为类md5形式以进行压缩。即使您的服务端采用python或java或go，当然我看到您的服务端为nodejs，都可以实现您的需求，不管是服务内部传输还是web端都可以减少压力。（曾经我的玩家数据json后的字符串达到了近2M）。我对您的持久化方式不了解，如果想要依靠orm直接存储的话，对网络的开销可能会比较大。
2. 您提到的`数据存储时的完整性`具体含义是什么呢？如果有可能的话，希望能帮到您。
感谢您的时间，同时也感谢您对开源社区做出的贡献。

**Comment by WhiteMinds** [comment]
> 我也曾多次萌发想要开发一款类似的text-based-idle-game,但是因为繁杂的事务让我无暇分心。 在称呼上，关于`您`大可不必在意，这是基本的尊重。
> 
> 1. lzstring可以对JSON.stringfy后的结构化数据编码为类md5形式以进行压缩。即使您的服务端采用python或java或go，当然我看到您的服务端为nodejs，都可以实现您的需求，不管是服务内部传输还是web端都可以减少压力。（曾经我的玩家数据json后的字符串达到了近2M）。我对您的持久化方式不了解，如果想要依靠orm直接存储的话，对网络的开销可能会比较大。
> 2. 您提到的`数据存储时的完整性`具体含义是什么呢？如果有可能的话，希望能帮到您。
>    感谢您的时间，同时也感谢您对开源社区做出的贡献。

1. 可以以后看看，如果确实有需要压缩字符串的场景可以试试。
2. 现在 createEntity 会调用 store.create，但数据更新不会调用 update，而是等 engine.destroy 时才调用。
这会导致数据的完整性出现问题，服务端强制终止时，create 时的数据被持久化了，后续的 update 没有被持久化，大概有几种方向：
  i. 任何需要持久化的数据发生变动时都要通知 store，这将使引擎的代码增加许多，并影响到后续的设计
  ii. 创建不经过 store，而是引擎生成一个临时 id，并持有一个临时 id 到真实 id 的 Record<UniqueId, UniqueId | null>，在要求持久化时，对数据做处理。
  iii. 创建时，store 记录还未主动要求持久化的数据 id，在下次启动时检查到强制终止时做处理
🤔 只是简单想了几个方向，还没仔细想优缺点，周末光顾着打游戏了，这两天下班之后再看看，你有遇到过类似的场景吗？

**Comment by ppxb** [comment]
因为我之前做的demo都是基于短连接的，只有在特定场合才会和服务端通信。从您的表述看出，您的程序强依赖服务端。
您提到的这个问题，其实可以参照分布式事务的方式来解决。我对您的代码还没来得及深入研究，仅提供一种可能性。
使用两阶段或三阶段提交可以高度保持数据的一致性。
您提到的方案ii+iii其实就是该方法的一种变形，如果不通过store直接创建，则将其归类为cache并和真实实例绑定；在需要持久化时，通过绑定id将cache和真实实例进行对比，如果产生冲突则只保留一个可信度更高的结果。
个人思路可能偏向通过redis作为缓冲层，将cache存入redis中，不管是异常中断还是正常关机，都可以达到优雅下线的效果。

**Comment by WhiteMinds** [comment]
> 因为我之前做的demo都是基于短连接的，只有在特定场合才会和服务端通信。从您的表述看出，您的程序强依赖服务端。 您提到的这个问题，其实可以参照分布式事务的方式来解决。我对您的代码还没来得及深入研究，仅提供一种可能性。 使用两阶段或三阶段提交可以高度保持数据的一致性。 您提到的方案ii+iii其实就是该方法的一种变形，如果不通过store直接创建，则将其归类为cache并和真实实例绑定；在需要持久化时，通过绑定id将cache和真实实例进行对比，如果产生冲突则只保留一个可信度更高的结果。 个人思路可能偏向通过redis作为缓冲层，将cache存入redis中，不管是异常中断还是正常关机，都可以达到优雅下线的效果。

这个项目确实算是强依赖服务端的，客户端只是作为渲染和交互的手段，单机模式只不过是允许浏览器自己持有一个本地服务端（这个是参考了 mc 的设计）。
分布式事务我没看过，对于分布式和数据库我都挺感兴趣的，以前感觉比较复杂没有场景所以没研究，这两天抽空看看，感觉会有帮助。
redis 的话想过，不过应该是作为 Store 的实现细节来做，主要是 Store 抽象和 Engine 间的交互问题，Store 自己可以决定被调用后怎么处理数据，Engine 只负责通知 Store 哪些数据变化了。
我现在之所以不想每次 Engine 有数据变化就通知 Store，是因为这样要写比较多的重复代码并且性能上有负担（每次给 Store 的都得是序列化后的数据），除非有一种比较好的模式可以简化这个步骤。
